todolist/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

todolist/todo/urls.py
from django.contrib import admin
from django.urls import path
from .views import IndexView, DetailView, DeleteView, UpdateView, TodoCreate
from .views import delete_todo
from .views import contact_form
app_name = 'todo'

urlpatterns = [
    path('', IndexView.as_view(), name='todolist'),
    path('detail/<int:pk>/', DetailView.as_view(), name="todolist_detail"),
    path('delete/<int:pk>/', DeleteView.as_view(), name="todolist_delete"),
    path('delete_todo/<int:pk>/', delete_todo, name="delete_todo"),
    path('update/<int:pk>/', UpdateView.as_view(), name='todolist_update'),
    path('create/', TodoCreate, name='todolist_create'),
    path('contact/', contact_form, name='contactform'),
]

todolist/todo/models.py
from django.db import models
from datetime import date
import datetime
from django.contrib.auth.models import User

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=40, verbose_name="할일제목")
    description = models.TextField(max_length=200, verbose_name="할일세부사항")
    date_created = models.DateField(auto_now_add=True, verbose_name="생성날짜")
    date_deadline = models.DateField(verbose_name="데드라인")
    
    def remaining_days(self):
        delta = self.date_deadline - date.today()
        days = delta.days 
        return days

    def __str__(self):
        return f'{self.name} | {self.description} | {self.date_created} | {self.date_deadline}'

    class Meta:
        verbose_name = "투두리스트"
        verbose_name_plural = "투두리스트"

class TodoList_images(models.Model):
    todo = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='todo/images/%Y/%m', blank=True)


class TodoList_files(models.Model):
    todo = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    files = models.FileField(upload_to='todo/files/%Y/%m', blank=True)


class ContactUs(models.Model):
    name = models.CharField(max_length=100, verbose_name="Contact_From")
    email = models.EmailField(max_length=100, verbose_name="이메일")
    phone_number = models.CharField(max_length=12, verbose_name="전화번호")
    message = models.TextField(max_length=500, verbose_name="연락내용")
    is_processed = models.BooleanField(default=False, blank=True, verbose_name="처리 완료 하시겠습니까?")

    def is_it_processed(self):
        if self.is_processed:
            return "처리완료"
        else:
            return "처리대기"

    def __str__(self):
        return f'{self.name} | {self.email} | {self.phone_number}'

    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

todolist/todo/forms.py
from django import forms
import datetime


class TodoContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'input',
                'placeholder': '이름',
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'input',
                'placeholder': '이메일',
            }
        )
    )

    phone_number = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'class': 'input',
                'placeholder': '전화번호',
            }

        )
    )

    message = forms.CharField(
        widget = forms.Textarea(
            attrs={
                'class': 'textarea',
                'placeholder': '메시지를 입력해주세요',
            }
        )
    )

class TodoCreateForm(forms.Form):

    name = forms.CharField(
        max_length=20,
        widget=forms.TextInput(
            attrs={
                'class': 'input',
                'placeholder': '해야할일',
            }
        )
    )

    description = forms.CharField(
        max_length=200,
        widget=forms.Textarea(
            attrs={
                'class': 'textarea',
                'placeholder': '할일에 대한 디테일',
            }
        )
    )

    date_deadline = forms.DateField(initial=datetime.date.today,
    # initial = datetime.date.today 로 정해서, 적어도 오늘 날짜로 폼이 미리 채워져서 
    # 에러를 방지할수 있음.. 
        widget=forms.DateInput(format='%Y-%m-%d',
            attrs={
                'id': 'from-datepicker',
                'placeholder': 'YYYY-MM-DD',
            }
        )
    )

    images = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'multiple': True,
                'class': 'file-input',
            }
        ), required=False,
    )

    files = forms.FileField(
        widget=forms.ClearableFileInput(
            attrs={
                'multiple': True,
                'class': 'file-input',
            }
        ), required=False,
    )

todolist/todo/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views import generic
from django.urls import reverse_lazy
from datetime import date, datetime
from .models import TodoList, TodoList_files, TodoList_images
from .models import ContactUs
from .forms import TodoCreateForm, TodoContactForm
# Create your views here.


def contact_form(request):
    if request.method == "POST":
        form = TodoContactForm(request.POST)
        if form.is_valid():
            name = request.POST['name']
            email = request.POST['email']
            phone_number = request.POST['phone_number']
            message = request.POST['message']

            c = ContactUs(
                name=name,
                email=email,
                phone_number=phone_number,
                message=message,
            )
            c.save()
            return HttpResponse("<script>window.onload = function(){alert('메시지가 접수되었습니다.'); document.location.href='/';}</script>")
        return render(request, 'contact.html', {'form': form})
    else:
        form = TodoContactForm()
        return render(request, 'contact.html', {'form': form})


def delete_todo(request, pk):
    t = TodoList.objects.get(pk=pk)
    t.delete() 
    return redirect('/')


class IndexView(generic.ListView):
    context_object_name = 'to_do_list'
    

    def get_queryset(self):
        return TodoList.objects.all()


class DetailView(generic.DetailView):
    model = TodoList
    context_object_name = 'todolist'
    
    def get_queryset(self):
        return TodoList.objects.all()


class DeleteView(generic.DeleteView):
    model = TodoList
    success_url = '/'
    template_name = 'todo/delete.html'



class UpdateView(generic.UpdateView):
    model = TodoList
    fields = ['name', 'description', 'date_deadline']
    template_name = 'todo/update.html'
    success_url = "/"



def TodoCreate(request):
    if request.method == "POST":
        
        form = TodoCreateForm(request.POST)
        if form.is_valid():
            try: 
                name = request.POST['name']
                description = request.POST['description']
                date_deadline = request.POST['date_deadline']
                images = request.FILES.getlist('images')
                files = request.FILES.getlist('files')
                date_created= date.today()

        # valid 한 date_deadline value 를 넣지 않았을때 
        # 막을 방법이 없음. 
        # date_created 가 date_deadline 보다 지난 날짜에 생성도 되는 문제점

                t = TodoList.objects.create(
                name=name, 
                description=description,
                date_created=date_created, 
                date_deadline=date_deadline,
                )
                t.save()

                for image in images:
                    TodoList_images.objects.create(todo=t, image=image)

                for file_in_list in files:
                    TodoList_files.objects.create(todo=t, files=file_in_list)

                return redirect('/')
            except ValueError:
                return HttpResponse('enter the right value for the date')
        else:       
            return render(request, 'todo/create.html', {'form': form})     
    else:
        form = TodoCreateForm()
        return render(request, 'todo/create.html', {'form': form})

todolist/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <title>To do List - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bulma/css/style.css' %}"> 

    {% block head %} {% endblock %}
</head>
<body>

  <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'todo:todolist' %}">
        <img src="{% static 'images/todo_list.jpg' %}" width="112" height="28">
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        
  
      <div class="navbar-end">
        <a class="navbar-item" href="{% url 'todo:todolist' %}">
          Home
        </a>
  
        <a class="navbar-item" href="{% url 'todo:todolist' %}">
          My Todos
        </a>
  
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            추가기능
          </a>
  
          <div class="navbar-dropdown">
            
            
            <hr class="navbar-divider">
            <a class="navbar-item" href="{% url 'todo:contactform' %}">
              Contact Us
            </a>
          </div>
        </div>
      </div>
        <div class="navbar-item">
          <div class="buttons">
            
            {% if user.is_authenticated %}
            <a class="button is-primary" href="{% url 'account_logout' %}">
              Log Out
            </a>
            {% else %}
            <a class="button is-primary" href="{% url 'account_signup' %}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{% url 'account_login' %}">
              Log in
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

 
  {% block content %} 

  {% endblock %}
  



   


</body>
</html>

todolist/templates/contact.html
{% extends 'base.html' %}


{% block content %}

<div class="field">
<div class="columns is-centered">

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}

    <div class="field" style="margin-top: 10px;">
      {{ field.name }}
      <div class="control">
          {{ field }}
      </div>
    </div>
    {% endfor %}
    <div class="control">
        <button class="button is-link">Submit</button>
      </div>
</form>

</div>
</div>




{% endblock %}

todolist/templates/todo/create.html
{% extends 'base.html' %}

{% block head %} 
<script   src="https://code.jquery.com/jquery-2.2.3.min.js"   integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="   crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker3.min.css">
<script>
$( document ).ready(function() {
    $("#from-datepicker").datepicker({ 
        format: 'yyyy-mm-dd'
    });
    $("#from-datepicker").on("change", function () {
        var fromdate = $(this).val();
        alert(fromdate);
    });
}); 
</script>


{% endblock %}



{% block content %}


   
<article class="message is-info">
    <div class="message-header">
      <p>Todo List 추가</p>
      <button class="delete" aria-label="delete"></button>
    </div>
    <div class="message-body">
      새로운 투두 리스트를 추가해 보세요! 
    </div>
  </article>

<div class="columns is-centered">
 

<form action="" method="POST" enctype="multipart/form-data" style="margin-top: 50px;">
{% csrf_token %}
{% for field in form %}


{% if field.name == 'images' or field.name == 'files' %}


{{ field.name }}
<div class="file has-name" style="margin-top: 10px;">
    <label class="file-label">
      {{ field }}
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Choose {{ field.name }} to upload
        </span>
      </span>
      <span class="file-name">
        Upload your {{ field.name }} here
      </span>
    </label>
  </div>
  


{% else %}

    <div class="field" style="margin-top: 10px;">
        {{ field.name }}
        <div class="control">
        {{ field }}
    </div>
    </div>
    {% endif %}
    {% endfor %}

    <div class="field is-grouped is-grouped-centered" style="margin-top: 30px;">
        <div class="control">
          <button class="button is-link">Submit</button>
        </div>
        <div class="control">
          <button class="button is-danger is-light">Cancel</button>
        </div>
      </div>
</form> 
</div>


 

{% endblock %}

todolist/templates/todo/delete.html
{% load static %}



<link rel="stylesheet" type="text/css" href="{% static 'bulma/css/style.css' %}">




<div class="field is-grouped is-grouped-centered">
    <p>{{ object }}</p><br><br>
    
</div>

<div class="field is-grouped is-grouped-centered">
    
    <form action="" method="POST">
    
    {{ form }}
    {% csrf_token %}

    <p class="control">
        
      <input type="submit" class="button is-danger" value="삭제">
      <a class="button is-light" href="{% url 'todo:todolist' %}">
        취소
      </a>
    </p>

    
    </form>


</div>

<div class="field is-grouped is-grouped-centered">
    
    <p class="control">
        해당 투두리스트를 삭제 하시겠습니까?
      </p>
  </div>

todolist/templates/todo/todolist_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <title>To do List - 
      {% block title %}할일 정보{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bulma/css/style.css' %}"> 



{% block content %}

</head>
<body>

  <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'todo:todolist' %}">
        <img src="{% static 'images/todo_list.jpg' %}" width="112" height="28">
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        
  
      <div class="navbar-end">
        <a class="navbar-item">
          Home
        </a>
  
        <a class="navbar-item" href="{% url 'todo:todolist' %}">
          My ToDo
        </a>
  
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>
  
          <div class="navbar-dropdown">
            <a class="navbar-item">
              취업정보
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
              버그 신고하기
            </a>
          </div>
        </div>
      </div>
        <div class="navbar-item">
          <div class="buttons">
            {% if user.is_authenticated %}
            <a class="button is-primary" href="{% url 'account_logout' %}">
              Log Out
            </a>
            {% else %}
            <a class="button is-primary" href="{% url 'account_signup' %}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{% url 'account_login' %}">
              Log in
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>


<div class="columns">

    
    <div class="card column">
        <header class="card-header">
          <p class="card-header-title">
            할일 : {{ todolist.name }} {{ id_list }}
          </p>
          <a href="#" class="card-header-icon" aria-label="more options">
            <span class="icon">
              <i class="fas fa-angle-down" aria-hidden="true"></i>
            </span>
          </a>
        </header>
        <div class="card-content">
          <div class="content">
            해야 할일 : {{ todolist.description }}
            <br>
            <hr>
            생성 날짜 : {{ todolist.date_created }}
            <br>
            데드 라인 : {{ todolist.date_deadline }}
            <hr>
            남은 일수 : {{ todolist.remaining_days }}
            <hr>
            관련 이미지 : 
            {% for image in todolist.todolist_images_set.all %}
            <img src="{{ image.image.url }}" width="300px" height="350px" alt="reference_image">
            {% endfor %}
            <hr>
            관련 파일 : <br><br>
            {% for file in todolist.todolist_files_set.all %}
            {{ file.files.url }}
            <a href="{{ file.files.url }}">(파일보기)</a><br>

            {% endfor %}
          </div>
        </div>
        <footer class="card-footer">
          <a href="{% url 'todo:todolist' %}" class="card-footer-item"><button class="button is-link is-fullwidth">뒤로가기</button></a>
          <a href="/update/{{ todolist.pk }}" class="card-footer-item"><button class="button is-warning is-fullwidth">수정하기</button></a>
          <a href="/delete_todo/{{ todolist.pk }}" class="card-footer-item">
          <button class="button is-danger is-fullwidth">삭제하기</button>
          </a>
        </footer>
      </div>
      

{% endblock content %}

todolist/templates/todo/todolist_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}할일 목록{% endblock %}

{% block content %}
<hr>
{% if user.is_authenticated %}
<div class="box has-text-centered">
  <a href="{% url 'todo:todolist_create' %}">
<button class="button is-info is-rounded">할일 추가하기</button>
</a>
</div>
{% else %}

{% endif %}

<div class="columns">
{% for todo in to_do_list %}

<div class="card column">
    <header class="card-header">
      <p class="card-header-title">
        할일 : {{ todo.name }}
      </p>
      <a href="#" class="card-header-icon" aria-label="more options">
        <span class="icon">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </a>
    </header>
    <div class="card-content">
      <div class="content">
        {{ todo.description|truncatechars:10 }}
        <br>
        <hr>
        생성 날짜 : {{ todo.date_created }}
        <br>
        데드 라인 : {{ todo.date_deadline }}
        <hr>
        남은 일수 : {{ todo.remaining_days }}
      </div>
    </div>
    <footer class="card-footer">
      <a href="/detail/{{ todo.id }}" class="card-footer-item"><button class="button is-primary is-fullwidth">더보기</button></a>
      <a href="/update/{{ todo.id }}" class="card-footer-item"><button class="button is-warning is-fullwidth">수정하기</button></a>
      <a href="/delete/{{ todo.id }}" class="card-footer-item"><button class="button is-danger is-fullwidth">삭제하기</button></a>
    </footer>
  </div>

{% endfor %}

</div>

<img src="{% static 'images/main.jpg' %}" width="100%">


{% endblock content %}

todolist/templates/todo/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <title>To do List - 
      {% block title %}할일 정보{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bulma/css/style.css' %}"> 




</head>
<body>

  <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="{% static 'images/todo_list.jpg' %}" width="112" height="28">
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        
  
      <div class="navbar-end">
        <a class="navbar-item" href="/">
          Home
        </a>
  
        <a class="navbar-item" href="/">
          To Do Lists
        </a>
  
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>
  
          <div class="navbar-dropdown">
            <a class="navbar-item">
              취업정보
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
              버그 신고하기
            </a>
          </div>
        </div>
      </div>
        <div class="navbar-item">
          <div class="buttons">
            {% if user.is_authenticated %}
            <a class="button is-primary" href="{% url 'account_logout' %}">
              Log Out
            </a>
            {% else %}
            <a class="button is-primary" href="{% url 'account_signup' %}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{% url 'account_login' %}">
              Log in
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>


  <div class="field is-grouped is-grouped-centered">

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button is-link" value="Update">
    </form>

  </div>

</body>
</html>

todolist/todo/templates/todo/todo-lists.html
{% extends 'bulma/base.html' %}

{% block title %}내가 할일 뭐지?{% endblock %}

{% block content %}
  
<ul>
{% for todo in to_do_list %}

<li>할일 제목 : {{ todo.name }}</li>


<li>생성 날짜 : {{ todo.date_created }}</li>

<li>데드라인 날짜 : {{ todo.date_deadline }}</li>

<li>남은 일수 : {{ todo.remaining_days }}</li>

{% endfor %}
</ul>

{% endblock content %}