dstagram/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

app_name = 'account'

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LoginView.as_view(template_name='registration/logout.html'), name='logout'),
]

dstagram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from account.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('account.urls')),
    path('register/', register, name='register')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dstagram/photo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import DetailView

from .views import photo_list, CreateView, DeleteView, PhotoDeleteView, PhotoUploadView, PhotoUpdateView
from .models import Photo



# app_name 은 namespace로 사용되는 값. 템플릿에서 url 템플릿 태그를 사용할때 app_name 값이 설정 되어 있다면
# [app_name:URL패턴이름] 형태로 사용

# 제너릭 뷰인 DetailView 는 urls.py에서 인라인 코드로 작성 가능. path 함수에 인수로 전달할 때는 as_view안에 클래스 변수들을 설정해 사용

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

dstagram/photo/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
from django.urls import reverse


class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')
    # Foreign Key 를 사용하여, User 테이블과 관계를 만듦.
    # User 모델은, 장고에서 기본적으로 사용하는 사용자 모델
    # on_delete = models.CASCADE 는 연결된 모델이 삭제될 경우, 현재 모델의 값은 어떻게 할것 이냐 결정함.
    # 삭제 될때의 동작은 CASCADE, PROTECTED, SET_NULL, SET_DEFAULT, SET(), DO_NOTHING 등이 있다.

    ## related_name 은 연결된 객체에서 하위 객체의 목록을 부를때 사용할 이름.
    #### 어떤 user가 작성한 글을 불러 올때는 유저 객체에 user_photos 속성을 참조.

    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # auto_now_add = True : 객체가 추가될때 자동으로 값을 설정
    # auto_now=True : 객체가 수정될때마다 자동으로 값을 설정

    class Meta:
        ordering = ['-updated']
        # ordering 은 해당 모델의 객체를 어떤 기준으로 정렬할것 인지 설정하는 옵션
        # -updated 로 설정 : 글 수정 시간의 내림차순으로 정렬될것.

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d%H:%M:%S")

    # __str__메서드는 작성자의 이름과 글 작성일을 합친 문자열을 반환

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])

    # get_absolute_url 은 객체의 상세 페이지의 주소를 반환하는 메서드
    # 객체 추가 혹은 수정햇을때 이동할 주소를 위해 호출
    # 템플릿에서 상세 화면으로 이동하는 링크를 만들때 호출
    # reverse 는 URL 패턴 이름을 가지고 해당 패턴을 찾아 주소를 만들어주는 함수

dstagram/account/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms.widgets import Input


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

dstagram/account/views.py
from django.shortcuts import render

# Create your views here.

from .forms import RegisterForm


def register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_uesr': new_user})
        else:
            user_form = RegisterForm()

    return render(request, 'registration/register.html', {'form': user_form})

dstagram/photo/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import CreateView, DeleteView, UpdateView

from .models import Photo


def photo_list(request):
    photos = Photo.objects.all()
    # photo = {
    #     'photos': photos
    # }
    return render(request, 'photo/list.html', {'photos': photos})

# 함수형 뷰 vs 클래스형 뷰


class PhotoUploadView(CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'
    # template_name = 실제 사용할 템플릿을 설정

    # form_valid 메서드는 업로드를 끝낸후 이동할 페이지를 호출하기 위해 사용하는 메서드
    def form_valid(self, form):
        # 작성자는 현재 로그인 한 사용자로 설정
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            # 작성자를 설정하면, is_valid 메서드를 이용해 입력된 값들을 검증
            # 이상이 없다면 데이터베이스에 저장 후 메인페이지로 이동.
            form.instance.save()
            return redirect('/')
        else:
            # 이상이 있을 경우, 작성된 내용을 그대로 작성 페이지에 표시
            return self.render_to_response({'form': form})


class PhotoDeleteView(DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'


class PhotoUpdateView(UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'

dstagram/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<title>Dstagram {% block title %} {% endblock %}</title>




</head>
<body>




    <div class="container">
        <header class="header clearfix">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="/">Dstagram</a>
                <ul class="nav">
                    <li class="nav-item">
                        <a href="/" class="active nav-link">Home</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="#" class="nav-link">Welcome, {{ user.get_username }}</a></li>
                    <li class="nav-item"><a href="{% url 'photo:photo_upload' %}" class="nav-link">Upload</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">LogOut</a></li>

                    {% else %}
                    <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">LogIn</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">SignUp</a></li>
                    {% endif %}
                </ul>

            </nav>

        </header>

        {% block content %}
        {% endblock %}

        <footer class="footer">
            <p>&copy: 2018 Baepeu. Powered by Django 2</p>
        </footer>

    </div>

</body>
</html>