dstagram/photo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import DetailView

from .views import photo_list, CreateView, DeleteView, PhotoDeleteView, PhotoUploadView, PhotoUpdateView
from .models import Photo



# app_name 은 namespace로 사용되는 값. 템플릿에서 url 템플릿 태그를 사용할때 app_name 값이 설정 되어 있다면
# [app_name:URL패턴이름] 형태로 사용

# 제너릭 뷰인 DetailView 는 urls.py에서 인라인 코드로 작성 가능. path 함수에 인수로 전달할 때는 as_view안에 클래스 변수들을 설정해 사용

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

dstagram/photo/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
from django.urls import reverse


class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')
    # Foreign Key 를 사용하여, User 테이블과 관계를 만듦.
    # User 모델은, 장고에서 기본적으로 사용하는 사용자 모델
    # on_delete = models.CASCADE 는 연결된 모델이 삭제될 경우, 현재 모델의 값은 어떻게 할것 이냐 결정함.
    # 삭제 될때의 동작은 CASCADE, PROTECTED, SET_NULL, SET_DEFAULT, SET(), DO_NOTHING 등이 있다.

    ## related_name 은 연결된 객체에서 하위 객체의 목록을 부를때 사용할 이름.
    #### 어떤 user가 작성한 글을 불러 올때는 유저 객체에 user_photos 속성을 참조.

    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # auto_now_add = True : 객체가 추가될때 자동으로 값을 설정
    # auto_now=True : 객체가 수정될때마다 자동으로 값을 설정

    class Meta:
        ordering = ['-updated']
        # ordering 은 해당 모델의 객체를 어떤 기준으로 정렬할것 인지 설정하는 옵션
        # -updated 로 설정 : 글 수정 시간의 내림차순으로 정렬될것.

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d%H:%M:%S")

    # __str__메서드는 작성자의 이름과 글 작성일을 합친 문자열을 반환

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])

    # get_absolute_url 은 객체의 상세 페이지의 주소를 반환하는 메서드
    # 객체 추가 혹은 수정햇을때 이동할 주소를 위해 호출
    # 템플릿에서 상세 화면으로 이동하는 링크를 만들때 호출
    # reverse 는 URL 패턴 이름을 가지고 해당 패턴을 찾아 주소를 만들어주는 함수

dstagram/photo/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import CreateView, DeleteView, UpdateView

from .models import Photo


def photo_list(request):
    photos = Photo.objects.all()
    # photo = {
    #     'photos': photos
    # }
    return render(request, 'photo/list.html', {'photos': photos})

# 함수형 뷰 vs 클래스형 뷰


class PhotoUploadView(CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'
    # template_name = 실제 사용할 템플릿을 설정

    # form_valid 메서드는 업로드를 끝낸후 이동할 페이지를 호출하기 위해 사용하는 메서드
    def form_valid(self, form):
        # 작성자는 현재 로그인 한 사용자로 설정
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            # 작성자를 설정하면, is_valid 메서드를 이용해 입력된 값들을 검증
            # 이상이 없다면 데이터베이스에 저장 후 메인페이지로 이동.
            form.instance.save()
            return redirect('/')
        else:
            # 이상이 있을 경우, 작성된 내용을 그대로 작성 페이지에 표시
            return self.render_to_response({'form': form})


class PhotoDeleteView(DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'


class PhotoUpdateView(UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'

dstagram/photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %} - Delete {% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">

            Do you want to delete {{object}}?
        </div>

        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Confirm">

        </form>

    </div>




    <div class="col-md-2"></div>




</div>



{% endblock %}

dstagram/photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %}
    {{ object.text | truncatechars:10 }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{ object.photo.url }}" style="width: 100%;"></p>
            <button type="button" class="btn btn-outline-primary btn-sm">
                {{ object.author.username }}
            </button>
            <p>{{ object.text|linebreaksbr }}</p>

            <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
                Delete
            </a>

            <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-success btn-sm float-right">
                Update
            </a>

        </div>
        <div class="col-md-2"></div>
    </div>



{% endblock %}

dstagram/photo/templates/photo/list.html
{% extends 'base.html' %}

{% block title %} - List {% endblock %}

{% block content %}
    {% for post in photos %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{ post.photo.url }}" style="width:100%;"></p>
                <button type="button" class="btn btn-xs btn-info">
                    {{ post.author.username }}
                </button>
                <p>{{ post.text|linebreaksbr }}</p>
                <p class="text-right">
                    <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn-xs btn-success">
                        댓글달기
                    </a>

                </p>

            </div>

            <div class="col-md-2"></div>


        </div>

    {% endfor %}
{% endblock %}

dstagram/photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}
- Update
{% endblock %}

{% block content %}

<div class="row">

        <div class="col-md-2"></div>
        <div class="col-md-8 panel pane-default">

            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Update">

            </form>


        </div>

    <div class="col-md-2"></div>



</div>





{% endblock %}

<!--
enctype 은 Method 가 POST 일때만 사용 가능

1 . application/x-www-form-urlencoded : 기본옵션. 모든 문자열을 인코딩해 전달.
2.  multipart/form-data : 파일 업로드때 사용하는 옵션이며, 데이터를 문자열로 인코딩 안하고 전달.
3.  text/plain : 띄어쓰기만 +로 변환 특별한 인코딩 없이 전달.

-->

dstagram/photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %} - Upload {% endblock %}

{% block content %}

<div class="row">

    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">

        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Upload">


        </form>


    </div>
    <div class="col-md-2"></div>


</div>




{% endblock %}